// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Milkado/api-challenge-jornada-milhas/ent/destinies"
	"github.com/Milkado/api-challenge-jornada-milhas/ent/predicate"
)

// DestiniesUpdate is the builder for updating Destinies entities.
type DestiniesUpdate struct {
	config
	hooks    []Hook
	mutation *DestiniesMutation
}

// Where appends a list predicates to the DestiniesUpdate builder.
func (du *DestiniesUpdate) Where(ps ...predicate.Destinies) *DestiniesUpdate {
	du.mutation.Where(ps...)
	return du
}

// SetName sets the "name" field.
func (du *DestiniesUpdate) SetName(s string) *DestiniesUpdate {
	du.mutation.SetName(s)
	return du
}

// SetNillableName sets the "name" field if the given value is not nil.
func (du *DestiniesUpdate) SetNillableName(s *string) *DestiniesUpdate {
	if s != nil {
		du.SetName(*s)
	}
	return du
}

// SetPicture sets the "picture" field.
func (du *DestiniesUpdate) SetPicture(s string) *DestiniesUpdate {
	du.mutation.SetPicture(s)
	return du
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (du *DestiniesUpdate) SetNillablePicture(s *string) *DestiniesUpdate {
	if s != nil {
		du.SetPicture(*s)
	}
	return du
}

// SetPrice sets the "price" field.
func (du *DestiniesUpdate) SetPrice(f float64) *DestiniesUpdate {
	du.mutation.ResetPrice()
	du.mutation.SetPrice(f)
	return du
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (du *DestiniesUpdate) SetNillablePrice(f *float64) *DestiniesUpdate {
	if f != nil {
		du.SetPrice(*f)
	}
	return du
}

// AddPrice adds f to the "price" field.
func (du *DestiniesUpdate) AddPrice(f float64) *DestiniesUpdate {
	du.mutation.AddPrice(f)
	return du
}

// SetCreatedAt sets the "created_at" field.
func (du *DestiniesUpdate) SetCreatedAt(t time.Time) *DestiniesUpdate {
	du.mutation.SetCreatedAt(t)
	return du
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (du *DestiniesUpdate) SetNillableCreatedAt(t *time.Time) *DestiniesUpdate {
	if t != nil {
		du.SetCreatedAt(*t)
	}
	return du
}

// SetUpdatedAt sets the "updated_at" field.
func (du *DestiniesUpdate) SetUpdatedAt(t time.Time) *DestiniesUpdate {
	du.mutation.SetUpdatedAt(t)
	return du
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (du *DestiniesUpdate) SetNillableUpdatedAt(t *time.Time) *DestiniesUpdate {
	if t != nil {
		du.SetUpdatedAt(*t)
	}
	return du
}

// Mutation returns the DestiniesMutation object of the builder.
func (du *DestiniesUpdate) Mutation() *DestiniesMutation {
	return du.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (du *DestiniesUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, du.sqlSave, du.mutation, du.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (du *DestiniesUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DestiniesUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DestiniesUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

func (du *DestiniesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(destinies.Table, destinies.Columns, sqlgraph.NewFieldSpec(destinies.FieldID, field.TypeInt))
	if ps := du.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.Name(); ok {
		_spec.SetField(destinies.FieldName, field.TypeString, value)
	}
	if value, ok := du.mutation.Picture(); ok {
		_spec.SetField(destinies.FieldPicture, field.TypeString, value)
	}
	if value, ok := du.mutation.Price(); ok {
		_spec.SetField(destinies.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := du.mutation.AddedPrice(); ok {
		_spec.AddField(destinies.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := du.mutation.CreatedAt(); ok {
		_spec.SetField(destinies.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := du.mutation.UpdatedAt(); ok {
		_spec.SetField(destinies.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{destinies.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	du.mutation.done = true
	return n, nil
}

// DestiniesUpdateOne is the builder for updating a single Destinies entity.
type DestiniesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DestiniesMutation
}

// SetName sets the "name" field.
func (duo *DestiniesUpdateOne) SetName(s string) *DestiniesUpdateOne {
	duo.mutation.SetName(s)
	return duo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (duo *DestiniesUpdateOne) SetNillableName(s *string) *DestiniesUpdateOne {
	if s != nil {
		duo.SetName(*s)
	}
	return duo
}

// SetPicture sets the "picture" field.
func (duo *DestiniesUpdateOne) SetPicture(s string) *DestiniesUpdateOne {
	duo.mutation.SetPicture(s)
	return duo
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (duo *DestiniesUpdateOne) SetNillablePicture(s *string) *DestiniesUpdateOne {
	if s != nil {
		duo.SetPicture(*s)
	}
	return duo
}

// SetPrice sets the "price" field.
func (duo *DestiniesUpdateOne) SetPrice(f float64) *DestiniesUpdateOne {
	duo.mutation.ResetPrice()
	duo.mutation.SetPrice(f)
	return duo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (duo *DestiniesUpdateOne) SetNillablePrice(f *float64) *DestiniesUpdateOne {
	if f != nil {
		duo.SetPrice(*f)
	}
	return duo
}

// AddPrice adds f to the "price" field.
func (duo *DestiniesUpdateOne) AddPrice(f float64) *DestiniesUpdateOne {
	duo.mutation.AddPrice(f)
	return duo
}

// SetCreatedAt sets the "created_at" field.
func (duo *DestiniesUpdateOne) SetCreatedAt(t time.Time) *DestiniesUpdateOne {
	duo.mutation.SetCreatedAt(t)
	return duo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (duo *DestiniesUpdateOne) SetNillableCreatedAt(t *time.Time) *DestiniesUpdateOne {
	if t != nil {
		duo.SetCreatedAt(*t)
	}
	return duo
}

// SetUpdatedAt sets the "updated_at" field.
func (duo *DestiniesUpdateOne) SetUpdatedAt(t time.Time) *DestiniesUpdateOne {
	duo.mutation.SetUpdatedAt(t)
	return duo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (duo *DestiniesUpdateOne) SetNillableUpdatedAt(t *time.Time) *DestiniesUpdateOne {
	if t != nil {
		duo.SetUpdatedAt(*t)
	}
	return duo
}

// Mutation returns the DestiniesMutation object of the builder.
func (duo *DestiniesUpdateOne) Mutation() *DestiniesMutation {
	return duo.mutation
}

// Where appends a list predicates to the DestiniesUpdate builder.
func (duo *DestiniesUpdateOne) Where(ps ...predicate.Destinies) *DestiniesUpdateOne {
	duo.mutation.Where(ps...)
	return duo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (duo *DestiniesUpdateOne) Select(field string, fields ...string) *DestiniesUpdateOne {
	duo.fields = append([]string{field}, fields...)
	return duo
}

// Save executes the query and returns the updated Destinies entity.
func (duo *DestiniesUpdateOne) Save(ctx context.Context) (*Destinies, error) {
	return withHooks(ctx, duo.sqlSave, duo.mutation, duo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DestiniesUpdateOne) SaveX(ctx context.Context) *Destinies {
	node, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (duo *DestiniesUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DestiniesUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (duo *DestiniesUpdateOne) sqlSave(ctx context.Context) (_node *Destinies, err error) {
	_spec := sqlgraph.NewUpdateSpec(destinies.Table, destinies.Columns, sqlgraph.NewFieldSpec(destinies.FieldID, field.TypeInt))
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Destinies.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := duo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, destinies.FieldID)
		for _, f := range fields {
			if !destinies.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != destinies.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := duo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := duo.mutation.Name(); ok {
		_spec.SetField(destinies.FieldName, field.TypeString, value)
	}
	if value, ok := duo.mutation.Picture(); ok {
		_spec.SetField(destinies.FieldPicture, field.TypeString, value)
	}
	if value, ok := duo.mutation.Price(); ok {
		_spec.SetField(destinies.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := duo.mutation.AddedPrice(); ok {
		_spec.AddField(destinies.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := duo.mutation.CreatedAt(); ok {
		_spec.SetField(destinies.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := duo.mutation.UpdatedAt(); ok {
		_spec.SetField(destinies.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Destinies{config: duo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{destinies.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	duo.mutation.done = true
	return _node, nil
}
