// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Milkado/api-challenge-jornada-milhas/ent/destinies"
	"github.com/Milkado/api-challenge-jornada-milhas/ent/destinypictures"
	"github.com/Milkado/api-challenge-jornada-milhas/ent/predicate"
)

// DestinyPicturesQuery is the builder for querying DestinyPictures entities.
type DestinyPicturesQuery struct {
	config
	ctx           *QueryContext
	order         []destinypictures.OrderOption
	inters        []Interceptor
	predicates    []predicate.DestinyPictures
	withDestinies *DestiniesQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DestinyPicturesQuery builder.
func (dpq *DestinyPicturesQuery) Where(ps ...predicate.DestinyPictures) *DestinyPicturesQuery {
	dpq.predicates = append(dpq.predicates, ps...)
	return dpq
}

// Limit the number of records to be returned by this query.
func (dpq *DestinyPicturesQuery) Limit(limit int) *DestinyPicturesQuery {
	dpq.ctx.Limit = &limit
	return dpq
}

// Offset to start from.
func (dpq *DestinyPicturesQuery) Offset(offset int) *DestinyPicturesQuery {
	dpq.ctx.Offset = &offset
	return dpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dpq *DestinyPicturesQuery) Unique(unique bool) *DestinyPicturesQuery {
	dpq.ctx.Unique = &unique
	return dpq
}

// Order specifies how the records should be ordered.
func (dpq *DestinyPicturesQuery) Order(o ...destinypictures.OrderOption) *DestinyPicturesQuery {
	dpq.order = append(dpq.order, o...)
	return dpq
}

// QueryDestinies chains the current query on the "destinies" edge.
func (dpq *DestinyPicturesQuery) QueryDestinies() *DestiniesQuery {
	query := (&DestiniesClient{config: dpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(destinypictures.Table, destinypictures.FieldID, selector),
			sqlgraph.To(destinies.Table, destinies.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, destinypictures.DestiniesTable, destinypictures.DestiniesColumn),
		)
		fromU = sqlgraph.SetNeighbors(dpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DestinyPictures entity from the query.
// Returns a *NotFoundError when no DestinyPictures was found.
func (dpq *DestinyPicturesQuery) First(ctx context.Context) (*DestinyPictures, error) {
	nodes, err := dpq.Limit(1).All(setContextOp(ctx, dpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{destinypictures.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dpq *DestinyPicturesQuery) FirstX(ctx context.Context) *DestinyPictures {
	node, err := dpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DestinyPictures ID from the query.
// Returns a *NotFoundError when no DestinyPictures ID was found.
func (dpq *DestinyPicturesQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dpq.Limit(1).IDs(setContextOp(ctx, dpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{destinypictures.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dpq *DestinyPicturesQuery) FirstIDX(ctx context.Context) int {
	id, err := dpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DestinyPictures entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DestinyPictures entity is found.
// Returns a *NotFoundError when no DestinyPictures entities are found.
func (dpq *DestinyPicturesQuery) Only(ctx context.Context) (*DestinyPictures, error) {
	nodes, err := dpq.Limit(2).All(setContextOp(ctx, dpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{destinypictures.Label}
	default:
		return nil, &NotSingularError{destinypictures.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dpq *DestinyPicturesQuery) OnlyX(ctx context.Context) *DestinyPictures {
	node, err := dpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DestinyPictures ID in the query.
// Returns a *NotSingularError when more than one DestinyPictures ID is found.
// Returns a *NotFoundError when no entities are found.
func (dpq *DestinyPicturesQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dpq.Limit(2).IDs(setContextOp(ctx, dpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{destinypictures.Label}
	default:
		err = &NotSingularError{destinypictures.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dpq *DestinyPicturesQuery) OnlyIDX(ctx context.Context) int {
	id, err := dpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DestinyPicturesSlice.
func (dpq *DestinyPicturesQuery) All(ctx context.Context) ([]*DestinyPictures, error) {
	ctx = setContextOp(ctx, dpq.ctx, "All")
	if err := dpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DestinyPictures, *DestinyPicturesQuery]()
	return withInterceptors[[]*DestinyPictures](ctx, dpq, qr, dpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dpq *DestinyPicturesQuery) AllX(ctx context.Context) []*DestinyPictures {
	nodes, err := dpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DestinyPictures IDs.
func (dpq *DestinyPicturesQuery) IDs(ctx context.Context) (ids []int, err error) {
	if dpq.ctx.Unique == nil && dpq.path != nil {
		dpq.Unique(true)
	}
	ctx = setContextOp(ctx, dpq.ctx, "IDs")
	if err = dpq.Select(destinypictures.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dpq *DestinyPicturesQuery) IDsX(ctx context.Context) []int {
	ids, err := dpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dpq *DestinyPicturesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dpq.ctx, "Count")
	if err := dpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dpq, querierCount[*DestinyPicturesQuery](), dpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dpq *DestinyPicturesQuery) CountX(ctx context.Context) int {
	count, err := dpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dpq *DestinyPicturesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dpq.ctx, "Exist")
	switch _, err := dpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dpq *DestinyPicturesQuery) ExistX(ctx context.Context) bool {
	exist, err := dpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DestinyPicturesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dpq *DestinyPicturesQuery) Clone() *DestinyPicturesQuery {
	if dpq == nil {
		return nil
	}
	return &DestinyPicturesQuery{
		config:        dpq.config,
		ctx:           dpq.ctx.Clone(),
		order:         append([]destinypictures.OrderOption{}, dpq.order...),
		inters:        append([]Interceptor{}, dpq.inters...),
		predicates:    append([]predicate.DestinyPictures{}, dpq.predicates...),
		withDestinies: dpq.withDestinies.Clone(),
		// clone intermediate query.
		sql:  dpq.sql.Clone(),
		path: dpq.path,
	}
}

// WithDestinies tells the query-builder to eager-load the nodes that are connected to
// the "destinies" edge. The optional arguments are used to configure the query builder of the edge.
func (dpq *DestinyPicturesQuery) WithDestinies(opts ...func(*DestiniesQuery)) *DestinyPicturesQuery {
	query := (&DestiniesClient{config: dpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dpq.withDestinies = query
	return dpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Picture string `json:"picture,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DestinyPictures.Query().
//		GroupBy(destinypictures.FieldPicture).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dpq *DestinyPicturesQuery) GroupBy(field string, fields ...string) *DestinyPicturesGroupBy {
	dpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DestinyPicturesGroupBy{build: dpq}
	grbuild.flds = &dpq.ctx.Fields
	grbuild.label = destinypictures.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Picture string `json:"picture,omitempty"`
//	}
//
//	client.DestinyPictures.Query().
//		Select(destinypictures.FieldPicture).
//		Scan(ctx, &v)
func (dpq *DestinyPicturesQuery) Select(fields ...string) *DestinyPicturesSelect {
	dpq.ctx.Fields = append(dpq.ctx.Fields, fields...)
	sbuild := &DestinyPicturesSelect{DestinyPicturesQuery: dpq}
	sbuild.label = destinypictures.Label
	sbuild.flds, sbuild.scan = &dpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DestinyPicturesSelect configured with the given aggregations.
func (dpq *DestinyPicturesQuery) Aggregate(fns ...AggregateFunc) *DestinyPicturesSelect {
	return dpq.Select().Aggregate(fns...)
}

func (dpq *DestinyPicturesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dpq); err != nil {
				return err
			}
		}
	}
	for _, f := range dpq.ctx.Fields {
		if !destinypictures.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dpq.path != nil {
		prev, err := dpq.path(ctx)
		if err != nil {
			return err
		}
		dpq.sql = prev
	}
	return nil
}

func (dpq *DestinyPicturesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DestinyPictures, error) {
	var (
		nodes       = []*DestinyPictures{}
		_spec       = dpq.querySpec()
		loadedTypes = [1]bool{
			dpq.withDestinies != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DestinyPictures).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DestinyPictures{config: dpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dpq.withDestinies; query != nil {
		if err := dpq.loadDestinies(ctx, query, nodes, nil,
			func(n *DestinyPictures, e *Destinies) { n.Edges.Destinies = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dpq *DestinyPicturesQuery) loadDestinies(ctx context.Context, query *DestiniesQuery, nodes []*DestinyPictures, init func(*DestinyPictures), assign func(*DestinyPictures, *Destinies)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DestinyPictures)
	for i := range nodes {
		fk := nodes[i].DestinyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(destinies.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "destiny_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (dpq *DestinyPicturesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dpq.querySpec()
	_spec.Node.Columns = dpq.ctx.Fields
	if len(dpq.ctx.Fields) > 0 {
		_spec.Unique = dpq.ctx.Unique != nil && *dpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dpq.driver, _spec)
}

func (dpq *DestinyPicturesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(destinypictures.Table, destinypictures.Columns, sqlgraph.NewFieldSpec(destinypictures.FieldID, field.TypeInt))
	_spec.From = dpq.sql
	if unique := dpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dpq.path != nil {
		_spec.Unique = true
	}
	if fields := dpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, destinypictures.FieldID)
		for i := range fields {
			if fields[i] != destinypictures.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if dpq.withDestinies != nil {
			_spec.Node.AddColumnOnce(destinypictures.FieldDestinyID)
		}
	}
	if ps := dpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dpq *DestinyPicturesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dpq.driver.Dialect())
	t1 := builder.Table(destinypictures.Table)
	columns := dpq.ctx.Fields
	if len(columns) == 0 {
		columns = destinypictures.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dpq.sql != nil {
		selector = dpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dpq.ctx.Unique != nil && *dpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dpq.predicates {
		p(selector)
	}
	for _, p := range dpq.order {
		p(selector)
	}
	if offset := dpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DestinyPicturesGroupBy is the group-by builder for DestinyPictures entities.
type DestinyPicturesGroupBy struct {
	selector
	build *DestinyPicturesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dpgb *DestinyPicturesGroupBy) Aggregate(fns ...AggregateFunc) *DestinyPicturesGroupBy {
	dpgb.fns = append(dpgb.fns, fns...)
	return dpgb
}

// Scan applies the selector query and scans the result into the given value.
func (dpgb *DestinyPicturesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dpgb.build.ctx, "GroupBy")
	if err := dpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DestinyPicturesQuery, *DestinyPicturesGroupBy](ctx, dpgb.build, dpgb, dpgb.build.inters, v)
}

func (dpgb *DestinyPicturesGroupBy) sqlScan(ctx context.Context, root *DestinyPicturesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dpgb.fns))
	for _, fn := range dpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dpgb.flds)+len(dpgb.fns))
		for _, f := range *dpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DestinyPicturesSelect is the builder for selecting fields of DestinyPictures entities.
type DestinyPicturesSelect struct {
	*DestinyPicturesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dps *DestinyPicturesSelect) Aggregate(fns ...AggregateFunc) *DestinyPicturesSelect {
	dps.fns = append(dps.fns, fns...)
	return dps
}

// Scan applies the selector query and scans the result into the given value.
func (dps *DestinyPicturesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dps.ctx, "Select")
	if err := dps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DestinyPicturesQuery, *DestinyPicturesSelect](ctx, dps.DestinyPicturesQuery, dps, dps.inters, v)
}

func (dps *DestinyPicturesSelect) sqlScan(ctx context.Context, root *DestinyPicturesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dps.fns))
	for _, fn := range dps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
