// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Milkado/api-challenge-jornada-milhas/ent/predicate"
	"github.com/Milkado/api-challenge-jornada-milhas/ent/testimonies"
)

// TestimoniesUpdate is the builder for updating Testimonies entities.
type TestimoniesUpdate struct {
	config
	hooks    []Hook
	mutation *TestimoniesMutation
}

// Where appends a list predicates to the TestimoniesUpdate builder.
func (tu *TestimoniesUpdate) Where(ps ...predicate.Testimonies) *TestimoniesUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetTestimony sets the "testimony" field.
func (tu *TestimoniesUpdate) SetTestimony(s string) *TestimoniesUpdate {
	tu.mutation.SetTestimony(s)
	return tu
}

// SetNillableTestimony sets the "testimony" field if the given value is not nil.
func (tu *TestimoniesUpdate) SetNillableTestimony(s *string) *TestimoniesUpdate {
	if s != nil {
		tu.SetTestimony(*s)
	}
	return tu
}

// SetName sets the "name" field.
func (tu *TestimoniesUpdate) SetName(s string) *TestimoniesUpdate {
	tu.mutation.SetName(s)
	return tu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tu *TestimoniesUpdate) SetNillableName(s *string) *TestimoniesUpdate {
	if s != nil {
		tu.SetName(*s)
	}
	return tu
}

// SetPicture sets the "picture" field.
func (tu *TestimoniesUpdate) SetPicture(s string) *TestimoniesUpdate {
	tu.mutation.SetPicture(s)
	return tu
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (tu *TestimoniesUpdate) SetNillablePicture(s *string) *TestimoniesUpdate {
	if s != nil {
		tu.SetPicture(*s)
	}
	return tu
}

// SetCreatedAt sets the "created_at" field.
func (tu *TestimoniesUpdate) SetCreatedAt(t time.Time) *TestimoniesUpdate {
	tu.mutation.SetCreatedAt(t)
	return tu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tu *TestimoniesUpdate) SetNillableCreatedAt(t *time.Time) *TestimoniesUpdate {
	if t != nil {
		tu.SetCreatedAt(*t)
	}
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TestimoniesUpdate) SetUpdatedAt(t time.Time) *TestimoniesUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tu *TestimoniesUpdate) SetNillableUpdatedAt(t *time.Time) *TestimoniesUpdate {
	if t != nil {
		tu.SetUpdatedAt(*t)
	}
	return tu
}

// Mutation returns the TestimoniesMutation object of the builder.
func (tu *TestimoniesUpdate) Mutation() *TestimoniesMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TestimoniesUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TestimoniesUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TestimoniesUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TestimoniesUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TestimoniesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(testimonies.Table, testimonies.Columns, sqlgraph.NewFieldSpec(testimonies.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Testimony(); ok {
		_spec.SetField(testimonies.FieldTestimony, field.TypeString, value)
	}
	if value, ok := tu.mutation.Name(); ok {
		_spec.SetField(testimonies.FieldName, field.TypeString, value)
	}
	if value, ok := tu.mutation.Picture(); ok {
		_spec.SetField(testimonies.FieldPicture, field.TypeString, value)
	}
	if value, ok := tu.mutation.CreatedAt(); ok {
		_spec.SetField(testimonies.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(testimonies.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{testimonies.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TestimoniesUpdateOne is the builder for updating a single Testimonies entity.
type TestimoniesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TestimoniesMutation
}

// SetTestimony sets the "testimony" field.
func (tuo *TestimoniesUpdateOne) SetTestimony(s string) *TestimoniesUpdateOne {
	tuo.mutation.SetTestimony(s)
	return tuo
}

// SetNillableTestimony sets the "testimony" field if the given value is not nil.
func (tuo *TestimoniesUpdateOne) SetNillableTestimony(s *string) *TestimoniesUpdateOne {
	if s != nil {
		tuo.SetTestimony(*s)
	}
	return tuo
}

// SetName sets the "name" field.
func (tuo *TestimoniesUpdateOne) SetName(s string) *TestimoniesUpdateOne {
	tuo.mutation.SetName(s)
	return tuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tuo *TestimoniesUpdateOne) SetNillableName(s *string) *TestimoniesUpdateOne {
	if s != nil {
		tuo.SetName(*s)
	}
	return tuo
}

// SetPicture sets the "picture" field.
func (tuo *TestimoniesUpdateOne) SetPicture(s string) *TestimoniesUpdateOne {
	tuo.mutation.SetPicture(s)
	return tuo
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (tuo *TestimoniesUpdateOne) SetNillablePicture(s *string) *TestimoniesUpdateOne {
	if s != nil {
		tuo.SetPicture(*s)
	}
	return tuo
}

// SetCreatedAt sets the "created_at" field.
func (tuo *TestimoniesUpdateOne) SetCreatedAt(t time.Time) *TestimoniesUpdateOne {
	tuo.mutation.SetCreatedAt(t)
	return tuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tuo *TestimoniesUpdateOne) SetNillableCreatedAt(t *time.Time) *TestimoniesUpdateOne {
	if t != nil {
		tuo.SetCreatedAt(*t)
	}
	return tuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TestimoniesUpdateOne) SetUpdatedAt(t time.Time) *TestimoniesUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tuo *TestimoniesUpdateOne) SetNillableUpdatedAt(t *time.Time) *TestimoniesUpdateOne {
	if t != nil {
		tuo.SetUpdatedAt(*t)
	}
	return tuo
}

// Mutation returns the TestimoniesMutation object of the builder.
func (tuo *TestimoniesUpdateOne) Mutation() *TestimoniesMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TestimoniesUpdate builder.
func (tuo *TestimoniesUpdateOne) Where(ps ...predicate.Testimonies) *TestimoniesUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TestimoniesUpdateOne) Select(field string, fields ...string) *TestimoniesUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Testimonies entity.
func (tuo *TestimoniesUpdateOne) Save(ctx context.Context) (*Testimonies, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TestimoniesUpdateOne) SaveX(ctx context.Context) *Testimonies {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TestimoniesUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TestimoniesUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TestimoniesUpdateOne) sqlSave(ctx context.Context) (_node *Testimonies, err error) {
	_spec := sqlgraph.NewUpdateSpec(testimonies.Table, testimonies.Columns, sqlgraph.NewFieldSpec(testimonies.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Testimonies.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, testimonies.FieldID)
		for _, f := range fields {
			if !testimonies.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != testimonies.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Testimony(); ok {
		_spec.SetField(testimonies.FieldTestimony, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Name(); ok {
		_spec.SetField(testimonies.FieldName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Picture(); ok {
		_spec.SetField(testimonies.FieldPicture, field.TypeString, value)
	}
	if value, ok := tuo.mutation.CreatedAt(); ok {
		_spec.SetField(testimonies.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(testimonies.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Testimonies{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{testimonies.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
