// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Milkado/api-challenge-jornada-milhas/ent/destinies"
	"github.com/Milkado/api-challenge-jornada-milhas/ent/predicate"
	"github.com/Milkado/api-challenge-jornada-milhas/ent/testimonies"
)

// TestimoniesQuery is the builder for querying Testimonies entities.
type TestimoniesQuery struct {
	config
	ctx           *QueryContext
	order         []testimonies.OrderOption
	inters        []Interceptor
	predicates    []predicate.Testimonies
	withDestinies *DestiniesQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TestimoniesQuery builder.
func (tq *TestimoniesQuery) Where(ps ...predicate.Testimonies) *TestimoniesQuery {
	tq.predicates = append(tq.predicates, ps...)
	return tq
}

// Limit the number of records to be returned by this query.
func (tq *TestimoniesQuery) Limit(limit int) *TestimoniesQuery {
	tq.ctx.Limit = &limit
	return tq
}

// Offset to start from.
func (tq *TestimoniesQuery) Offset(offset int) *TestimoniesQuery {
	tq.ctx.Offset = &offset
	return tq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tq *TestimoniesQuery) Unique(unique bool) *TestimoniesQuery {
	tq.ctx.Unique = &unique
	return tq
}

// Order specifies how the records should be ordered.
func (tq *TestimoniesQuery) Order(o ...testimonies.OrderOption) *TestimoniesQuery {
	tq.order = append(tq.order, o...)
	return tq
}

// QueryDestinies chains the current query on the "destinies" edge.
func (tq *TestimoniesQuery) QueryDestinies() *DestiniesQuery {
	query := (&DestiniesClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(testimonies.Table, testimonies.FieldID, selector),
			sqlgraph.To(destinies.Table, destinies.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, testimonies.DestiniesTable, testimonies.DestiniesColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Testimonies entity from the query.
// Returns a *NotFoundError when no Testimonies was found.
func (tq *TestimoniesQuery) First(ctx context.Context) (*Testimonies, error) {
	nodes, err := tq.Limit(1).All(setContextOp(ctx, tq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{testimonies.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tq *TestimoniesQuery) FirstX(ctx context.Context) *Testimonies {
	node, err := tq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Testimonies ID from the query.
// Returns a *NotFoundError when no Testimonies ID was found.
func (tq *TestimoniesQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(1).IDs(setContextOp(ctx, tq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{testimonies.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tq *TestimoniesQuery) FirstIDX(ctx context.Context) int {
	id, err := tq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Testimonies entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Testimonies entity is found.
// Returns a *NotFoundError when no Testimonies entities are found.
func (tq *TestimoniesQuery) Only(ctx context.Context) (*Testimonies, error) {
	nodes, err := tq.Limit(2).All(setContextOp(ctx, tq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{testimonies.Label}
	default:
		return nil, &NotSingularError{testimonies.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tq *TestimoniesQuery) OnlyX(ctx context.Context) *Testimonies {
	node, err := tq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Testimonies ID in the query.
// Returns a *NotSingularError when more than one Testimonies ID is found.
// Returns a *NotFoundError when no entities are found.
func (tq *TestimoniesQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(2).IDs(setContextOp(ctx, tq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{testimonies.Label}
	default:
		err = &NotSingularError{testimonies.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tq *TestimoniesQuery) OnlyIDX(ctx context.Context) int {
	id, err := tq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TestimoniesSlice.
func (tq *TestimoniesQuery) All(ctx context.Context) ([]*Testimonies, error) {
	ctx = setContextOp(ctx, tq.ctx, "All")
	if err := tq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Testimonies, *TestimoniesQuery]()
	return withInterceptors[[]*Testimonies](ctx, tq, qr, tq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tq *TestimoniesQuery) AllX(ctx context.Context) []*Testimonies {
	nodes, err := tq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Testimonies IDs.
func (tq *TestimoniesQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tq.ctx.Unique == nil && tq.path != nil {
		tq.Unique(true)
	}
	ctx = setContextOp(ctx, tq.ctx, "IDs")
	if err = tq.Select(testimonies.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tq *TestimoniesQuery) IDsX(ctx context.Context) []int {
	ids, err := tq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tq *TestimoniesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tq.ctx, "Count")
	if err := tq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tq, querierCount[*TestimoniesQuery](), tq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tq *TestimoniesQuery) CountX(ctx context.Context) int {
	count, err := tq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tq *TestimoniesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tq.ctx, "Exist")
	switch _, err := tq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tq *TestimoniesQuery) ExistX(ctx context.Context) bool {
	exist, err := tq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TestimoniesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tq *TestimoniesQuery) Clone() *TestimoniesQuery {
	if tq == nil {
		return nil
	}
	return &TestimoniesQuery{
		config:        tq.config,
		ctx:           tq.ctx.Clone(),
		order:         append([]testimonies.OrderOption{}, tq.order...),
		inters:        append([]Interceptor{}, tq.inters...),
		predicates:    append([]predicate.Testimonies{}, tq.predicates...),
		withDestinies: tq.withDestinies.Clone(),
		// clone intermediate query.
		sql:  tq.sql.Clone(),
		path: tq.path,
	}
}

// WithDestinies tells the query-builder to eager-load the nodes that are connected to
// the "destinies" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TestimoniesQuery) WithDestinies(opts ...func(*DestiniesQuery)) *TestimoniesQuery {
	query := (&DestiniesClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withDestinies = query
	return tq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Testimony string `json:"testimony,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Testimonies.Query().
//		GroupBy(testimonies.FieldTestimony).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tq *TestimoniesQuery) GroupBy(field string, fields ...string) *TestimoniesGroupBy {
	tq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TestimoniesGroupBy{build: tq}
	grbuild.flds = &tq.ctx.Fields
	grbuild.label = testimonies.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Testimony string `json:"testimony,omitempty"`
//	}
//
//	client.Testimonies.Query().
//		Select(testimonies.FieldTestimony).
//		Scan(ctx, &v)
func (tq *TestimoniesQuery) Select(fields ...string) *TestimoniesSelect {
	tq.ctx.Fields = append(tq.ctx.Fields, fields...)
	sbuild := &TestimoniesSelect{TestimoniesQuery: tq}
	sbuild.label = testimonies.Label
	sbuild.flds, sbuild.scan = &tq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TestimoniesSelect configured with the given aggregations.
func (tq *TestimoniesQuery) Aggregate(fns ...AggregateFunc) *TestimoniesSelect {
	return tq.Select().Aggregate(fns...)
}

func (tq *TestimoniesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tq); err != nil {
				return err
			}
		}
	}
	for _, f := range tq.ctx.Fields {
		if !testimonies.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tq.path != nil {
		prev, err := tq.path(ctx)
		if err != nil {
			return err
		}
		tq.sql = prev
	}
	return nil
}

func (tq *TestimoniesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Testimonies, error) {
	var (
		nodes       = []*Testimonies{}
		_spec       = tq.querySpec()
		loadedTypes = [1]bool{
			tq.withDestinies != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Testimonies).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Testimonies{config: tq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tq.withDestinies; query != nil {
		if err := tq.loadDestinies(ctx, query, nodes, nil,
			func(n *Testimonies, e *Destinies) { n.Edges.Destinies = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tq *TestimoniesQuery) loadDestinies(ctx context.Context, query *DestiniesQuery, nodes []*Testimonies, init func(*Testimonies), assign func(*Testimonies, *Destinies)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Testimonies)
	for i := range nodes {
		fk := nodes[i].DestinyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(destinies.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "destiny_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tq *TestimoniesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tq.querySpec()
	_spec.Node.Columns = tq.ctx.Fields
	if len(tq.ctx.Fields) > 0 {
		_spec.Unique = tq.ctx.Unique != nil && *tq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tq.driver, _spec)
}

func (tq *TestimoniesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(testimonies.Table, testimonies.Columns, sqlgraph.NewFieldSpec(testimonies.FieldID, field.TypeInt))
	_spec.From = tq.sql
	if unique := tq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tq.path != nil {
		_spec.Unique = true
	}
	if fields := tq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, testimonies.FieldID)
		for i := range fields {
			if fields[i] != testimonies.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tq.withDestinies != nil {
			_spec.Node.AddColumnOnce(testimonies.FieldDestinyID)
		}
	}
	if ps := tq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tq *TestimoniesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tq.driver.Dialect())
	t1 := builder.Table(testimonies.Table)
	columns := tq.ctx.Fields
	if len(columns) == 0 {
		columns = testimonies.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tq.sql != nil {
		selector = tq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tq.ctx.Unique != nil && *tq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tq.predicates {
		p(selector)
	}
	for _, p := range tq.order {
		p(selector)
	}
	if offset := tq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TestimoniesGroupBy is the group-by builder for Testimonies entities.
type TestimoniesGroupBy struct {
	selector
	build *TestimoniesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tgb *TestimoniesGroupBy) Aggregate(fns ...AggregateFunc) *TestimoniesGroupBy {
	tgb.fns = append(tgb.fns, fns...)
	return tgb
}

// Scan applies the selector query and scans the result into the given value.
func (tgb *TestimoniesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tgb.build.ctx, "GroupBy")
	if err := tgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TestimoniesQuery, *TestimoniesGroupBy](ctx, tgb.build, tgb, tgb.build.inters, v)
}

func (tgb *TestimoniesGroupBy) sqlScan(ctx context.Context, root *TestimoniesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tgb.fns))
	for _, fn := range tgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tgb.flds)+len(tgb.fns))
		for _, f := range *tgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TestimoniesSelect is the builder for selecting fields of Testimonies entities.
type TestimoniesSelect struct {
	*TestimoniesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ts *TestimoniesSelect) Aggregate(fns ...AggregateFunc) *TestimoniesSelect {
	ts.fns = append(ts.fns, fns...)
	return ts
}

// Scan applies the selector query and scans the result into the given value.
func (ts *TestimoniesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ts.ctx, "Select")
	if err := ts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TestimoniesQuery, *TestimoniesSelect](ctx, ts.TestimoniesQuery, ts, ts.inters, v)
}

func (ts *TestimoniesSelect) sqlScan(ctx context.Context, root *TestimoniesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ts.fns))
	for _, fn := range ts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
