// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Milkado/api-challenge-jornada-milhas/ent/predicate"
	"github.com/Milkado/api-challenge-jornada-milhas/ent/testimonies"
)

// TestimoniesDelete is the builder for deleting a Testimonies entity.
type TestimoniesDelete struct {
	config
	hooks    []Hook
	mutation *TestimoniesMutation
}

// Where appends a list predicates to the TestimoniesDelete builder.
func (td *TestimoniesDelete) Where(ps ...predicate.Testimonies) *TestimoniesDelete {
	td.mutation.Where(ps...)
	return td
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (td *TestimoniesDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, td.sqlExec, td.mutation, td.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (td *TestimoniesDelete) ExecX(ctx context.Context) int {
	n, err := td.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (td *TestimoniesDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(testimonies.Table, sqlgraph.NewFieldSpec(testimonies.FieldID, field.TypeInt))
	if ps := td.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, td.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	td.mutation.done = true
	return affected, err
}

// TestimoniesDeleteOne is the builder for deleting a single Testimonies entity.
type TestimoniesDeleteOne struct {
	td *TestimoniesDelete
}

// Where appends a list predicates to the TestimoniesDelete builder.
func (tdo *TestimoniesDeleteOne) Where(ps ...predicate.Testimonies) *TestimoniesDeleteOne {
	tdo.td.mutation.Where(ps...)
	return tdo
}

// Exec executes the deletion query.
func (tdo *TestimoniesDeleteOne) Exec(ctx context.Context) error {
	n, err := tdo.td.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{testimonies.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tdo *TestimoniesDeleteOne) ExecX(ctx context.Context) {
	if err := tdo.Exec(ctx); err != nil {
		panic(err)
	}
}
