// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Milkado/api-challenge-jornada-milhas/ent/destinies"
	"github.com/Milkado/api-challenge-jornada-milhas/ent/testimonies"
)

// TestimoniesCreate is the builder for creating a Testimonies entity.
type TestimoniesCreate struct {
	config
	mutation *TestimoniesMutation
	hooks    []Hook
}

// SetTestimony sets the "testimony" field.
func (tc *TestimoniesCreate) SetTestimony(s string) *TestimoniesCreate {
	tc.mutation.SetTestimony(s)
	return tc
}

// SetName sets the "name" field.
func (tc *TestimoniesCreate) SetName(s string) *TestimoniesCreate {
	tc.mutation.SetName(s)
	return tc
}

// SetPicture sets the "picture" field.
func (tc *TestimoniesCreate) SetPicture(s string) *TestimoniesCreate {
	tc.mutation.SetPicture(s)
	return tc
}

// SetDestinyID sets the "destiny_id" field.
func (tc *TestimoniesCreate) SetDestinyID(i int) *TestimoniesCreate {
	tc.mutation.SetDestinyID(i)
	return tc
}

// SetCreatedAt sets the "created_at" field.
func (tc *TestimoniesCreate) SetCreatedAt(t time.Time) *TestimoniesCreate {
	tc.mutation.SetCreatedAt(t)
	return tc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tc *TestimoniesCreate) SetNillableCreatedAt(t *time.Time) *TestimoniesCreate {
	if t != nil {
		tc.SetCreatedAt(*t)
	}
	return tc
}

// SetUpdatedAt sets the "updated_at" field.
func (tc *TestimoniesCreate) SetUpdatedAt(t time.Time) *TestimoniesCreate {
	tc.mutation.SetUpdatedAt(t)
	return tc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tc *TestimoniesCreate) SetNillableUpdatedAt(t *time.Time) *TestimoniesCreate {
	if t != nil {
		tc.SetUpdatedAt(*t)
	}
	return tc
}

// SetDestiniesID sets the "destinies" edge to the Destinies entity by ID.
func (tc *TestimoniesCreate) SetDestiniesID(id int) *TestimoniesCreate {
	tc.mutation.SetDestiniesID(id)
	return tc
}

// SetDestinies sets the "destinies" edge to the Destinies entity.
func (tc *TestimoniesCreate) SetDestinies(d *Destinies) *TestimoniesCreate {
	return tc.SetDestiniesID(d.ID)
}

// Mutation returns the TestimoniesMutation object of the builder.
func (tc *TestimoniesCreate) Mutation() *TestimoniesMutation {
	return tc.mutation
}

// Save creates the Testimonies in the database.
func (tc *TestimoniesCreate) Save(ctx context.Context) (*Testimonies, error) {
	if err := tc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, tc.sqlSave, tc.mutation, tc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TestimoniesCreate) SaveX(ctx context.Context) *Testimonies {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tc *TestimoniesCreate) Exec(ctx context.Context) error {
	_, err := tc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tc *TestimoniesCreate) ExecX(ctx context.Context) {
	if err := tc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tc *TestimoniesCreate) defaults() error {
	if _, ok := tc.mutation.CreatedAt(); !ok {
		if testimonies.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized testimonies.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := testimonies.DefaultCreatedAt()
		tc.mutation.SetCreatedAt(v)
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		if testimonies.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized testimonies.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := testimonies.DefaultUpdatedAt()
		tc.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (tc *TestimoniesCreate) check() error {
	if _, ok := tc.mutation.Testimony(); !ok {
		return &ValidationError{Name: "testimony", err: errors.New(`ent: missing required field "Testimonies.testimony"`)}
	}
	if _, ok := tc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Testimonies.name"`)}
	}
	if _, ok := tc.mutation.Picture(); !ok {
		return &ValidationError{Name: "picture", err: errors.New(`ent: missing required field "Testimonies.picture"`)}
	}
	if _, ok := tc.mutation.DestinyID(); !ok {
		return &ValidationError{Name: "destiny_id", err: errors.New(`ent: missing required field "Testimonies.destiny_id"`)}
	}
	if _, ok := tc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Testimonies.created_at"`)}
	}
	if _, ok := tc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Testimonies.updated_at"`)}
	}
	if _, ok := tc.mutation.DestiniesID(); !ok {
		return &ValidationError{Name: "destinies", err: errors.New(`ent: missing required edge "Testimonies.destinies"`)}
	}
	return nil
}

func (tc *TestimoniesCreate) sqlSave(ctx context.Context) (*Testimonies, error) {
	if err := tc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	tc.mutation.id = &_node.ID
	tc.mutation.done = true
	return _node, nil
}

func (tc *TestimoniesCreate) createSpec() (*Testimonies, *sqlgraph.CreateSpec) {
	var (
		_node = &Testimonies{config: tc.config}
		_spec = sqlgraph.NewCreateSpec(testimonies.Table, sqlgraph.NewFieldSpec(testimonies.FieldID, field.TypeInt))
	)
	if value, ok := tc.mutation.Testimony(); ok {
		_spec.SetField(testimonies.FieldTestimony, field.TypeString, value)
		_node.Testimony = value
	}
	if value, ok := tc.mutation.Name(); ok {
		_spec.SetField(testimonies.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := tc.mutation.Picture(); ok {
		_spec.SetField(testimonies.FieldPicture, field.TypeString, value)
		_node.Picture = value
	}
	if value, ok := tc.mutation.CreatedAt(); ok {
		_spec.SetField(testimonies.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := tc.mutation.UpdatedAt(); ok {
		_spec.SetField(testimonies.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := tc.mutation.DestiniesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   testimonies.DestiniesTable,
			Columns: []string{testimonies.DestiniesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(destinies.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DestinyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TestimoniesCreateBulk is the builder for creating many Testimonies entities in bulk.
type TestimoniesCreateBulk struct {
	config
	err      error
	builders []*TestimoniesCreate
}

// Save creates the Testimonies entities in the database.
func (tcb *TestimoniesCreateBulk) Save(ctx context.Context) ([]*Testimonies, error) {
	if tcb.err != nil {
		return nil, tcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tcb.builders))
	nodes := make([]*Testimonies, len(tcb.builders))
	mutators := make([]Mutator, len(tcb.builders))
	for i := range tcb.builders {
		func(i int, root context.Context) {
			builder := tcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TestimoniesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tcb *TestimoniesCreateBulk) SaveX(ctx context.Context) []*Testimonies {
	v, err := tcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcb *TestimoniesCreateBulk) Exec(ctx context.Context) error {
	_, err := tcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcb *TestimoniesCreateBulk) ExecX(ctx context.Context) {
	if err := tcb.Exec(ctx); err != nil {
		panic(err)
	}
}
