// Code generated by ent, DO NOT EDIT.

package users

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Milkado/api-challenge-jornada-milhas/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Users {
	return predicate.Users(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Users {
	return predicate.Users(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Users {
	return predicate.Users(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Users {
	return predicate.Users(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Users {
	return predicate.Users(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Users {
	return predicate.Users(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Users {
	return predicate.Users(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldName, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldEmail, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldPassword, v))
}

// RandSecurity applies equality check predicate on the "rand_security" field. It's identical to RandSecurityEQ.
func RandSecurity(v string) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldRandSecurity, v))
}

// PasswordToken applies equality check predicate on the "password_token" field. It's identical to PasswordTokenEQ.
func PasswordToken(v string) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldPasswordToken, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Users {
	return predicate.Users(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Users {
	return predicate.Users(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Users {
	return predicate.Users(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Users {
	return predicate.Users(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Users {
	return predicate.Users(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Users {
	return predicate.Users(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Users {
	return predicate.Users(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Users {
	return predicate.Users(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Users {
	return predicate.Users(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Users {
	return predicate.Users(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Users {
	return predicate.Users(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Users {
	return predicate.Users(sql.FieldContainsFold(FieldName, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Users {
	return predicate.Users(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Users {
	return predicate.Users(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Users {
	return predicate.Users(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Users {
	return predicate.Users(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Users {
	return predicate.Users(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Users {
	return predicate.Users(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Users {
	return predicate.Users(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Users {
	return predicate.Users(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Users {
	return predicate.Users(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Users {
	return predicate.Users(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Users {
	return predicate.Users(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Users {
	return predicate.Users(sql.FieldContainsFold(FieldEmail, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.Users {
	return predicate.Users(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.Users {
	return predicate.Users(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.Users {
	return predicate.Users(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.Users {
	return predicate.Users(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.Users {
	return predicate.Users(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.Users {
	return predicate.Users(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.Users {
	return predicate.Users(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.Users {
	return predicate.Users(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.Users {
	return predicate.Users(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.Users {
	return predicate.Users(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordIsNil applies the IsNil predicate on the "password" field.
func PasswordIsNil() predicate.Users {
	return predicate.Users(sql.FieldIsNull(FieldPassword))
}

// PasswordNotNil applies the NotNil predicate on the "password" field.
func PasswordNotNil() predicate.Users {
	return predicate.Users(sql.FieldNotNull(FieldPassword))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.Users {
	return predicate.Users(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.Users {
	return predicate.Users(sql.FieldContainsFold(FieldPassword, v))
}

// RandSecurityEQ applies the EQ predicate on the "rand_security" field.
func RandSecurityEQ(v string) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldRandSecurity, v))
}

// RandSecurityNEQ applies the NEQ predicate on the "rand_security" field.
func RandSecurityNEQ(v string) predicate.Users {
	return predicate.Users(sql.FieldNEQ(FieldRandSecurity, v))
}

// RandSecurityIn applies the In predicate on the "rand_security" field.
func RandSecurityIn(vs ...string) predicate.Users {
	return predicate.Users(sql.FieldIn(FieldRandSecurity, vs...))
}

// RandSecurityNotIn applies the NotIn predicate on the "rand_security" field.
func RandSecurityNotIn(vs ...string) predicate.Users {
	return predicate.Users(sql.FieldNotIn(FieldRandSecurity, vs...))
}

// RandSecurityGT applies the GT predicate on the "rand_security" field.
func RandSecurityGT(v string) predicate.Users {
	return predicate.Users(sql.FieldGT(FieldRandSecurity, v))
}

// RandSecurityGTE applies the GTE predicate on the "rand_security" field.
func RandSecurityGTE(v string) predicate.Users {
	return predicate.Users(sql.FieldGTE(FieldRandSecurity, v))
}

// RandSecurityLT applies the LT predicate on the "rand_security" field.
func RandSecurityLT(v string) predicate.Users {
	return predicate.Users(sql.FieldLT(FieldRandSecurity, v))
}

// RandSecurityLTE applies the LTE predicate on the "rand_security" field.
func RandSecurityLTE(v string) predicate.Users {
	return predicate.Users(sql.FieldLTE(FieldRandSecurity, v))
}

// RandSecurityContains applies the Contains predicate on the "rand_security" field.
func RandSecurityContains(v string) predicate.Users {
	return predicate.Users(sql.FieldContains(FieldRandSecurity, v))
}

// RandSecurityHasPrefix applies the HasPrefix predicate on the "rand_security" field.
func RandSecurityHasPrefix(v string) predicate.Users {
	return predicate.Users(sql.FieldHasPrefix(FieldRandSecurity, v))
}

// RandSecurityHasSuffix applies the HasSuffix predicate on the "rand_security" field.
func RandSecurityHasSuffix(v string) predicate.Users {
	return predicate.Users(sql.FieldHasSuffix(FieldRandSecurity, v))
}

// RandSecurityIsNil applies the IsNil predicate on the "rand_security" field.
func RandSecurityIsNil() predicate.Users {
	return predicate.Users(sql.FieldIsNull(FieldRandSecurity))
}

// RandSecurityNotNil applies the NotNil predicate on the "rand_security" field.
func RandSecurityNotNil() predicate.Users {
	return predicate.Users(sql.FieldNotNull(FieldRandSecurity))
}

// RandSecurityEqualFold applies the EqualFold predicate on the "rand_security" field.
func RandSecurityEqualFold(v string) predicate.Users {
	return predicate.Users(sql.FieldEqualFold(FieldRandSecurity, v))
}

// RandSecurityContainsFold applies the ContainsFold predicate on the "rand_security" field.
func RandSecurityContainsFold(v string) predicate.Users {
	return predicate.Users(sql.FieldContainsFold(FieldRandSecurity, v))
}

// PasswordTokenEQ applies the EQ predicate on the "password_token" field.
func PasswordTokenEQ(v string) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldPasswordToken, v))
}

// PasswordTokenNEQ applies the NEQ predicate on the "password_token" field.
func PasswordTokenNEQ(v string) predicate.Users {
	return predicate.Users(sql.FieldNEQ(FieldPasswordToken, v))
}

// PasswordTokenIn applies the In predicate on the "password_token" field.
func PasswordTokenIn(vs ...string) predicate.Users {
	return predicate.Users(sql.FieldIn(FieldPasswordToken, vs...))
}

// PasswordTokenNotIn applies the NotIn predicate on the "password_token" field.
func PasswordTokenNotIn(vs ...string) predicate.Users {
	return predicate.Users(sql.FieldNotIn(FieldPasswordToken, vs...))
}

// PasswordTokenGT applies the GT predicate on the "password_token" field.
func PasswordTokenGT(v string) predicate.Users {
	return predicate.Users(sql.FieldGT(FieldPasswordToken, v))
}

// PasswordTokenGTE applies the GTE predicate on the "password_token" field.
func PasswordTokenGTE(v string) predicate.Users {
	return predicate.Users(sql.FieldGTE(FieldPasswordToken, v))
}

// PasswordTokenLT applies the LT predicate on the "password_token" field.
func PasswordTokenLT(v string) predicate.Users {
	return predicate.Users(sql.FieldLT(FieldPasswordToken, v))
}

// PasswordTokenLTE applies the LTE predicate on the "password_token" field.
func PasswordTokenLTE(v string) predicate.Users {
	return predicate.Users(sql.FieldLTE(FieldPasswordToken, v))
}

// PasswordTokenContains applies the Contains predicate on the "password_token" field.
func PasswordTokenContains(v string) predicate.Users {
	return predicate.Users(sql.FieldContains(FieldPasswordToken, v))
}

// PasswordTokenHasPrefix applies the HasPrefix predicate on the "password_token" field.
func PasswordTokenHasPrefix(v string) predicate.Users {
	return predicate.Users(sql.FieldHasPrefix(FieldPasswordToken, v))
}

// PasswordTokenHasSuffix applies the HasSuffix predicate on the "password_token" field.
func PasswordTokenHasSuffix(v string) predicate.Users {
	return predicate.Users(sql.FieldHasSuffix(FieldPasswordToken, v))
}

// PasswordTokenIsNil applies the IsNil predicate on the "password_token" field.
func PasswordTokenIsNil() predicate.Users {
	return predicate.Users(sql.FieldIsNull(FieldPasswordToken))
}

// PasswordTokenNotNil applies the NotNil predicate on the "password_token" field.
func PasswordTokenNotNil() predicate.Users {
	return predicate.Users(sql.FieldNotNull(FieldPasswordToken))
}

// PasswordTokenEqualFold applies the EqualFold predicate on the "password_token" field.
func PasswordTokenEqualFold(v string) predicate.Users {
	return predicate.Users(sql.FieldEqualFold(FieldPasswordToken, v))
}

// PasswordTokenContainsFold applies the ContainsFold predicate on the "password_token" field.
func PasswordTokenContainsFold(v string) predicate.Users {
	return predicate.Users(sql.FieldContainsFold(FieldPasswordToken, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Users {
	return predicate.Users(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Users {
	return predicate.Users(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Users {
	return predicate.Users(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Users {
	return predicate.Users(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Users {
	return predicate.Users(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Users {
	return predicate.Users(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Users {
	return predicate.Users(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Users {
	return predicate.Users(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Users {
	return predicate.Users(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Users {
	return predicate.Users(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Users {
	return predicate.Users(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Users {
	return predicate.Users(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Users {
	return predicate.Users(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Users {
	return predicate.Users(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Users {
	return predicate.Users(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Users) predicate.Users {
	return predicate.Users(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Users) predicate.Users {
	return predicate.Users(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Users) predicate.Users {
	return predicate.Users(sql.NotPredicates(p))
}
