// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Destinies is the predicate function for destinies builders.
type Destinies func(*sql.Selector)

// DestinyPictures is the predicate function for destinypictures builders.
type DestinyPictures func(*sql.Selector)

// Testimonies is the predicate function for testimonies builders.
type Testimonies func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
